### ISSUE TITLE
windows11配置任务计划出错

### ISSUE THREAD

**Issue by kahakaha** [charlie0129/bupt-net-login#2]
我按照readme中的步骤创建了一个计划任务，但是计划任务无法正常执行，报错如下：
`任务计划程序无法为用户“xxx”启动“\bupt-net-login”任务。其他数据: 错误值: 2147943726。`

**Comment by kahakaha** [comment]
在常规选项卡中的安全选项一栏，我尝试勾选了不储存密码的选项，任务计划似乎就可以正常运行了
![image](https://github.com/charlie0129/bupt-net-login/assets/57161196/055a2435-7540-49ec-b6eb-924afdbbeb82)

**Comment by charlie0129** [comment]
好！我把你的解决方法加到 readme 中
