### ISSUE TITLE
手动登录失败

### ISSUE THREAD

**Issue by SaltedFish555** [charlie0129/bupt-net-login#3]
我的主机是win10系统，在ubuntu虚拟机里运行手动登录的脚本时，直接提示了已经登录，没有询问我的学号和网关密码。
但实际上我没有登录，经测试也无法打开信息门户网站。
主机连的是手机热点，手机开的流量。

**Comment by charlie0129** [comment]
既然连的是手机热点，已经可以正常访问网络了，那为何还要登录校园网呢。如果需要登录校园网，要首先接入校园网。

**Comment by SaltedFish555** [comment]
奥，抱歉，我可能误解了这个脚本的的作用，我以为是能连接webvpn，原来是连接无线网，抱歉抱歉。感谢回复

**Comment by charlie0129** [comment]
要连接 vpn 可以看看 https://github.com/docker-easyconnect/docker-easyconnect 。这个脚本是给 BUPT-Portal 和科研有线网用户认证用的

**Comment by SaltedFish555** [comment]
！非常感谢，我去鼓捣鼓捣
