### ISSUE TITLE
树莓派连接校园网遇到问题

### ISSUE THREAD

**Issue by liangruogu** [charlie0129/bupt-net-login#6]
第一次提Issue，还请多多体谅..

目前，我可以通过网线连接树莓派和电脑共享校园网（portal）给树莓派(没有外设，只有网线,HDMI,电脑)，但是我想设置学长的这个脚本为开机自启动（放在树莓派里），这样就可以让派在不插网线的时候连接校园网了。

我将脚本放在了根目录，并在/etc/rc.local的最后添加了开机执行脚本
<img width="646" alt="88c4d0cbe4fa34b6d792824f43ce109" src="https://github.com/charlie0129/bupt-net-login/assets/157556867/9f74c1ae-6abb-43e7-9f39-8b7452e88636">
而且我设置了环境变量（不知道这样设置对不对）
![2680772fcca69c3bf3314ea8c3d51aa](https://github.com/charlie0129/bupt-net-login/assets/157556867/84b72b88-332f-4076-bb1c-c08063de3e3d)
最后我重启派，断开网线，断掉树莓派电源再打开。一段时间后在终端通过 ssh liang@liangchurong.local连接我的派，发现失败了..

最后是树莓派的系统详情
<img width="487" alt="72a369656ffcf1c8d38f753182c800c" src="https://github.com/charlie0129/bupt-net-login/assets/157556867/72d4402e-df51-4cd0-92e3-b7c2ff2611c2">
<img width="304" alt="ceedc2302f677d11c4ee6d184baedc4" src="https://github.com/charlie0129/bupt-net-login/assets/157556867/10b484fc-e348-40c8-9059-ff2bf9199ece">
我的电脑是win11的系统

**Comment by charlie0129** [comment]
您好，我第一眼看过去可能（但不限于）有这样几个问题：

1. `/etc/rc.local` 添加的 `sudo bash ./home/...` 中正确的目录应为 `/home/...`；
2. 环境变量我不清楚您是如何添加的，`rc.local` 会在 login shell 启动之前执行，可能你的环境变量并没有添加进去。正确的方式应为 `BUPT_USERNAME=xxx BUPT_PASSWORD=xxx bash /home/...`。

为了方便看到错误输出，你可以把标准输出和错误输出重定向到文件，在命令后面添加 `2>&1 >/tmp/bupt.log`。

同时，开启启动就尝试登录一次可能会失败，因为：

1. 运行 `rc.local` 的时候，树莓派的 WiFi 还未连接，所以单次登录会失败，并且失败后后续也没有重试了；
2. 没有 handle 启动后掉登录的情况。‘

我认为对你你的 case 来说，建议的方式是按照 [README 中 cronjob 的方式](https://github.com/charlie0129/bupt-net-login?tab=readme-ov-file#cronjob) 运行，这是比较 robust 的方式，而不是手动添加开机执行。

**Comment by liangruogu** [comment]
嗯嗯，按照学长说的做了，使用cronjob为全部的用户都安装了

现在情况变得有点诡异，我将树莓派插在电脑或者宿舍的网线接口上时，可以找到它的ip也可以ssh连接，重启断电以后都可以再次连上。

但如果不插网线的话，就找不到ip, 呜~，也不清楚是怎么回事...

下面是bupt.log的内容
![image](https://github.com/charlie0129/bupt-net-login/assets/157556867/84176662-dfc0-4280-8cf2-41db7d7c51f5)
这里面似乎没有报错信息，不知道是不是执行一次都会覆盖还是..

还有一点是，不太清楚wpa_supplicant.conf应该如何配置
![image](https://github.com/charlie0129/bupt-net-login/assets/157556867/8291d6ea-155e-45e2-a89e-35db720dbb95)

**Comment by charlie0129** [comment]
> 现在情况变得有点诡异，我将树莓派插在电脑或者宿舍的网线接口上时，可以找到它的ip也可以ssh连接，重启断电以后都可以再次连上。

portal 可以保持登录一段时间的，关机一段时间也不会断

> 但如果不插网线的话，就找不到ip, 呜~，也不清楚是怎么回事...

不是很理解？

> 下面是bupt.log的内容 ![image](https://private-user-images.githubusercontent.com/157556867/337858550-84176662-dfc0-4280-8cf2-41db7d7c51f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4Mzc5NTgsIm5iZiI6MTcxNzgzNzY1OCwicGF0aCI6Ii8xNTc1NTY4NjcvMzM3ODU4NTUwLTg0MTc2NjYyLWRmYzAtNDI4MC04Y2YyLTQxZGI3ZDdjNTFmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwOTA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjE0YjBkYjk3ZmRlOTc0NWI3ZWM1M2YyZDBjNjAwOWI2NWYwNDMyY2VkZmQwMDVhOWYzM2Q3NGUxNzUxNzM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LICs1JE6fNvWBR5hVWnI5CDBq9p6P2cCikDzqzLIyiE) 这里面似乎没有报错信息，不知道是不是执行一次都会覆盖还是..

这个是正常能上网时候的情况

> 还有一点是，不太清楚wpa_supplicant.conf应该如何配置 ![image](https://private-user-images.githubusercontent.com/157556867/337859365-8291d6ea-155e-45e2-a89e-35db720dbb95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4Mzc5NTgsIm5iZiI6MTcxNzgzNzY1OCwicGF0aCI6Ii8xNTc1NTY4NjcvMzM3ODU5MzY1LTgyOTFkNmVhLTE1NWUtNDVlMi1hODllLTM1ZGI3MjBkYmI5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwOTA3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzJjOGUzMmRhYjgyZDAzNjM4MTJlNTFkZGUwYTliMjhhZGZkNDQyNjM3NTc3ZTVjODlkYTA2MzllZmVkYzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gc_nXsXk6H2J4mh2IxGU5I4BFSrmSmRWq_nGotPX5aU)

这你看看其他教程/文档吧？

**Comment by liangruogu** [comment]
谢谢,谢谢~
今天不知道为啥就可以连上了
