### ISSUE TITLE
cronjob按步骤操作毫无反应

### ISSUE THREAD

**Issue by liuhuayuan233** [charlie0129/bupt-net-login#7]
<img width="314" alt="屏幕截图 2024-09-26 225307" src="https://github.com/user-attachments/assets/dabdaf82-024b-4c75-a576-50cd90ec7983">

**Comment by charlie0129** [comment]
cat bupt-net-login.bin 看看内容

**Comment by liuhuayuan233** [comment]
> cat bupt-net-login.bin 看看内容

<img width="229" alt="image" src="https://github.com/user-attachments/assets/85fbc654-887a-4014-a021-c8a5ea1f8262">
tong同无反应

**Comment by charlie0129** [comment]
那这个文件就是空的，你啥都没下下来

**Comment by charlie0129** [comment]
正确下载之后应当可以正常使用了

**Comment by liuhuayuan233** [comment]
下载时文件有大小啊，我再重新下载试试，感谢

**Comment by charlie0129** [comment]
你可以贴出来怎么下载的，分享看看哪里有问题
